### ISSUE TITLE
Doesn't respect release character

### ISSUE THREAD

**Issue by Magomogo** [tdecaluwe/node-edifact#9] opened 2016-02-09 10:47 UTC
Quote from the documentation:

> Question mark "?" - release character
>   ?  immediately preceding one of the characters ' + : ?   restores their normal meaning.
>  E.g. 10?+10=20 means 10+10=20. Question mark is represented by ??.

**Comment by tdecaluwe** [comment] 2016-02-09 11:15
Duplicate of #5. This will be resolved in upcoming release as well.

**Comment by tdecaluwe** [comment] 2016-02-09 11:16
Duplicate of #5. This will be resolved in upcoming release as well.

**Closed as completed by tdecaluwe** 2016-02-09 11:16 UTC
Labels: duplicate

**Comment by Magomogo** [comment] 2016-02-09 11:19
Thanks for your work.

How deep are you in the refactoring? When to expect new release?

**Comment by tdecaluwe** [comment] 2016-02-09 11:43
I'm currently moving all the pieces into the right place, for example splitting out character set handling to a separate class. Afterwards the API will need updating to provide access to the new functionalities, and some smaller patches will have to be made (like the release character support). I'd say somewhere next week to get it on npm.
